import Head from "next/head";
import { type AppType } from "next/app";
import { EffectorNext } from "@effector/next";

import { api } from "~/shared/api";

import "react-grid-layout/css/styles.css";
import "react-resizable/css/styles.css";
import "~/styles/globals.css";

const MyApp: AppType<{ values: Record<string, unknown> }> = ({
  Component,
  pageProps,
}) => {
  return (
    <EffectorNext values={pageProps.values}>
      <Head>
        <title>Dynagraph</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </EffectorNext>
  );
};

export default api.withTRPC(MyApp);
