import Head from "next/head";

import { MainLayout } from "~/shared";

const Home = () => {
  return (
    <>
      <Head>
        <title>Dynagraph</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>123</MainLayout>
    </>
  );
};

export default Home;
