export {
  faChartColumn,
  faChartLine,
  faChartPie,
  faMicrochip,
  faCircleNodes,
  faNetworkWired,
  faGlobe,
  faClose,
  faSpinner,
  faPlus,
  faSort,
  faCheck,
  faEllipsisVertical,
  faTrash,
  faExpandArrowsAlt,
  faEdit,
  faPlay,
} from "@fortawesome/free-solid-svg-icons";
